FROM rocker/r-ver:4.3.0


RUN apt-get update && apt-get install -y \
    pandoc \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    && rm -rf /var/lib/apt/lists/*

RUN R -e "install.packages(c(\
    'rmarkdown', \
    'knitr', \
    'ggplot2', \
    'dplyr', \
    'tidyr', \
    'readr' \
    ), repos='https://cran.r-project.org')"

WORKDIR /notebook
