# Generated by Django 5.2.9 on 2025-12-28 03:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='execution',
            options={'ordering': ['-started_at'], 'verbose_name': 'Execution', 'verbose_name_plural': 'Executions'},
        ),
        migrations.AlterModelOptions(
            name='notebook',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Notebook', 'verbose_name_plural': 'Notebooks'},
        ),
        migrations.AlterModelOptions(
            name='reproducibilityanalysis',
            options={'verbose_name': 'Reproducibility Analysis', 'verbose_name_plural': 'Reproducibility Analyses'},
        ),
        migrations.AlterField(
            model_name='execution',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if execution failed'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='html_output',
            field=models.TextField(blank=True, help_text='Generated HTML output from R Markdown rendering'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='notebook',
            field=models.ForeignKey(help_text='The notebook that was executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='notebooks.notebook'),
        ),
        migrations.AlterField(
            model_name='execution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current execution status', max_length=20),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='author',
            field=models.ForeignKey(help_text='User who created this notebook', on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='content',
            field=models.TextField(blank=True, default='', help_text='R Markdown content'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this notebook is publicly visible'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(help_text='Notebook title (3-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(3, 'Title must be at least 3 characters')]),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='dependencies',
            field=models.JSONField(default=list, help_text='List of R package dependencies'),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='docker_image_tag',
            field=models.CharField(blank=True, help_text='Docker image tag if built', max_length=255),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='dockerfile',
            field=models.TextField(blank=True, default='', help_text='Generated Dockerfile content'),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='makefile',
            field=models.TextField(blank=True, default='', help_text='Generated Makefile content'),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='notebook',
            field=models.OneToOneField(help_text='The notebook being analyzed', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='notebooks.notebook'),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='r4r_score',
            field=models.IntegerField(default=0, help_text='Reproducibility score (0-100)'),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='system_deps',
            field=models.JSONField(default=list, help_text='List of system-level dependencies'),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='warnings',
            field=models.JSONField(default=list, help_text='List of reproducibility warnings'),
        ),
        migrations.AddIndex(
            model_name='execution',
            index=models.Index(fields=['notebook', '-started_at'], name='notebooks_e_noteboo_0b109f_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['-updated_at'], name='notebooks_n_updated_08282d_idx'),
        ),
        migrations.AddIndex(
            model_name='notebook',
            index=models.Index(fields=['author', '-updated_at'], name='notebooks_n_author__6a87ac_idx'),
        ),
    ]
