# Generated by Django 4.2.7 on 2025-12-04 00:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reproducibilityanalysis',
            name='analyzed_at',
        ),
        migrations.AddField(
            model_name='reproducibilityanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 4, 0, 14, 56, 243770, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reproducibilityanalysis',
            name='docker_image_tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reproducibilityanalysis',
            name='dockerfile',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reproducibilityanalysis',
            name='is_docker_built',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reproducibilityanalysis',
            name='makefile',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reproducibilityanalysis',
            name='r4r_output_dir',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='reproducibilityanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='notebook',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='notebooks.notebook'),
        ),
    ]
