# Generated by Django 4.2.7 on 2025-12-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_remove_reproducibilityanalysis_analyzed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reproducibilityanalysis',
            name='docker_image_tag',
        ),
        migrations.RemoveField(
            model_name='reproducibilityanalysis',
            name='is_docker_built',
        ),
        migrations.RemoveField(
            model_name='reproducibilityanalysis',
            name='r4r_output_dir',
        ),
    ]
