# Generated by Django 5.2.9 on 2025-12-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0002_alter_execution_options_alter_notebook_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reproducibilityanalysis',
            name='docker_image_tag',
        ),
        migrations.RemoveField(
            model_name='reproducibilityanalysis',
            name='r4r_score',
        ),
        migrations.RemoveField(
            model_name='reproducibilityanalysis',
            name='warnings',
        ),
        migrations.AddField(
            model_name='reproducibilityanalysis',
            name='diff_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='dependencies',
            field=models.JSONField(default=list, help_text='List of static analysis issues'),
        ),
    ]
