# Generated by Django 5.2.9 on 2025-12-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0003_remove_reproducibilityanalysis_docker_image_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproducibilityanalysis',
            name='r4r_data',
            field=models.JSONField(blank=True, default=dict, help_text='r4r build metrics: r_packages, system_libs, files_accessed'),
        ),
    ]
