# Generated by Django 5.2.9 on 2025-12-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebooks', '0004_reproducibilityanalysis_r4r_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='content',
            field=models.TextField(default='', help_text='R Markdown content'),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='dependencies',
            field=models.JSONField(default=list, help_text='List of R package dependencies'),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='diff_html',
            field=models.TextField(blank=True, help_text='HTML diff visualization from rdiff', null=True),
        ),
        migrations.AlterField(
            model_name='reproducibilityanalysis',
            name='r4r_data',
            field=models.JSONField(blank=True, default=dict, help_text='r4r metrics: r_packages, system_libs, files_accessed'),
        ),
    ]
